### ISSUE TITLE
[Design] Support for change address

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-lib#137]
Implementation PRs:
https://github.com/HathorNetwork/hathor-wallet-lib/pull/138
https://github.com/HathorNetwork/hathor-wallet-headless/pull/45

# Motivation

Our wallet lib always creates a new address to send the change amount when the sum of outputs if bigger than the sum of the inputs being spent. This is not good especially because we don't use a separate derivation for change addresses, as described in [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#change).

Some use cases have the requirement to keep all funds of a user in a single address or just would like not to use many addresses in their wallets, so it would be good to have this feature.

# Solution

## Wallet-lib

We have a method on `src/wallet.js` called `getOutputChange`.

```
  getOutputChange(value, tokenData) {
    const address = this.getAddressToUse();
    return {'address': address, 'value': value, 'tokenData': tokenData, 'isChange': true};
  }
```

We must add an optional parameter in this method, which is the change address. In case this address is null, we continue generating a new one.

This method is used in three situations:

1. Sending a transaction
2. Minting tokens
3. Melting tokens

I will add support for all three cases in the new `HathorWallet` (the facade) class. For that I will list the new method signatures that are used by the hathor-wallet-headless.

```
sendTransaction(address, value, token, options = { changeAddress: null })

sendManyOutputsTransaction(outputs, inputs = [], token = null, options = { changeAddress: null })

createNewToken(name, symbol, amount, address, options = { changeAddress: null })

mintTokens(tokenUid, amount, address, options = { changeAddress: null })

meltTokens(tokenUid, amount, options = { depositAddress: null, changeAddress: null })
```

In the `meltTokens` method I will also add the `depositAddress`, which is the address receive back the HTR deposit.

I am adding this `options` parameter in all methods that are used in the headless and will add it in all sequence of used methods until `getOutputChange`.

- In `src/new/wallet.js` we have: `completeTxData` and `prepareTransaction`.
- In `src/tokens.js` we have: `createToken`, `createMintData`, `mintTokens`, `createMeltData` and `meltTokens`.
- In `src/wallet.js` we have: `prepareSendTokensData` and `getOutputChange`.

### Validations

In `getOutputChange` we must validate that the address is valid in the network and it's an address from the loaded wallet.

### Tests

There are some tests on `__tests__/wallet.test.js` that use `prepareSendTokensData`. At least one of those should test the new change address parameter.

## Wallet-headless

We have two endpoints to send transactions: `simple-send-tx` and `send-tx`. We must add an optional parameter to both of them for a change address and send it to the methods in the facade.

This new parameter must also be added to the docs and the docs page must be updated.

## Wallet-desktop and wallet-mobile

I don't think we should add support for now in these wallets because it would make the UI more complex and with no need. I think this is a feature specific for use cases, then the wallet-headless is the one that should support it, at least for now.

# Tasks

1. Lib: Add `change_address` as optional parameter on `getOutputChange` and `prepareSendTokensData` in `src/wallet.js`. 
2. Lib: Add `change_address` as optional parameter on `sendManyOutputsTransaction`, `sendTransaction`, `prepareTransaction`, and `completeTxData` on `src/new/wallet.js`.
3. Lib: Add test for `change_address` parameter.
3. Add `change_address` as optional parameter on `simple-send-tx` and `send-tx` endpoints.
4. Add `change_address` optional parameter on docs

# Estimated time

The tasks above are simple, so it's hard to set an ETA for each one of them. So I would say that the whole design would take 1 day of work to finish.

**Comment by msbrogli** [comment]
> Discussion point: I won't validate that the change address received in the method is from the user wallet, should I?

That's a good point. I feel that we should validate that the address belongs to the wallet to protect misuse. Otherwise, the client just need to add a regular output.

**Comment by msbrogli** [comment]
I'd like to see the new signature of the methods with the parameter. Besides that, a list of verification that must be performed, e.g., whether the address is valid and belongs to the network the wallet is connected to.

I also think the minting and melting methods should allow the user to choose the "change address".

**Comment by pedroferreira1** [comment]
> That's a good point. I feel that we should validate that the address belongs to the wallet to protect misuse. Otherwise, the client just need to add a regular output.

Yeah, I agree. Will add the address validation to the code and design.

> I'd like to see the new signature of the methods with the parameter. Besides that, a list of verification that must be performed, e.g., whether the address is valid and belongs to the network the wallet is connected to.

I will add those to the design following your suggestion to have an `options` parameter.

> I also think the minting and melting methods should allow the user to choose the "change address".

I just finished looking at the code and it's not too complex to add support for it in the headless. For desktop/mobile the discussion would be about UI/UX, so I will keep them out for now. I will add to the design and the PRs the support for change address on create token (HTR deposit change), mint (HTR deposit change) and melt (token melt change).

**Comment by pedroferreira1** [comment]
@msbrogli design and code updated.

**Comment by msbrogli** [comment]
@pedroferreira1 Approved. Just a few considerations:

1) As we have a `depositAddress` for `meltTokens(...)` method, shouldn't we have a `mintAddress` to receive the newly created tokens in the `mintTokens(...)` and in the `createNewToken(...)  methods?

2) Should we allow different change addresses for each token? Or should we use the same address for all changes in the transaction? Even though using the same address feels natural, I feel it may have some privacy considerations (e.g. it may turned out to facilitate anyone to know how much was transferred).

**Comment by pedroferreira1** [comment]
> 1. As we have a depositAddress for meltTokens(...) method, shouldn't we have a mintAddress to receive the newly created tokens in the mintTokens(...) and in the `createNewToken(...) methods?

I added the `depositAddress` to melt now because we didn't have it before. However for `mintTokens` and `createNewToken` we already had.

```
createNewToken(name, symbol, amount, address, options = { changeAddress: null })

mintTokens(tokenUid, amount, address, options = { changeAddress: null })
```

`address` in both methods is the address you mentioned.

> 2. Should we allow different change addresses for each token? Or should we use the same address for all changes in the transaction? Even though using the same address feels natural, I feel it may have some privacy considerations (e.g. it may turned out to facilitate anyone to know how much was transferred).

We can discuss that but in my opinion this is not useful and it's not easy for the user to understand this parameter. Besides that, it's also not common to have more than one token in the same transaction. That's why I believe we should keep as simple as possible.

**Comment by thr0wn** [comment]
@pedroferreira1 Approved.
