### ISSUE TITLE
[Design] Wallet service integration

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-lib#145]
# Description

We have a new wallet service (https://github.com/HathorNetwork/hathor-wallet-service) in final stage of development, where we already have the following features implemented:

1. Load wallet
2. Get wallet status
3. Get addresses of a wallet
4. Get history of a wallet
5. Get balance of a wallet
6. Create a transaction

With this set of features ready we can start the integration of the hathor library with this new service, in order to be ready to use the service as soon as it's finished.

# Implementation

The idea is to create a new `HathorWallet` class in a new folder (can be `src/wallet/` where we will have all the files for the wallet integration). This new class will be inspired by the `src/new/wallet.js` class and will substitute the files in `src/new` in the future.

We will develop this new class fully in typescript following the refactor in this PR https://github.com/HathorNetwork/hathor-wallet-lib/pull/110.

I mention some wallet service APIs in the features description. For more details about the APIs, see https://github.com/HathorNetwork/hathor-wallet-service/issues/10.

### Axios wrapper for wallet service

We must create a new axios wrapper to send requests to wallet service. The lib must allow an easy way for the application to change the endpoint URL, in order to easily allow customizations and tests.

### Start wallet

The `HathorWallet` object will have a method `start(seed)`, which receives the seed.

We will receive the wallet words from the application (desktop, headless, mobile, ...) and from this seed we will generate the  in the account path from HD Wallet (see [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)). With this xpub we call `/wallet` POST API to start the wallet and get the corresponding `walletId`. This id will be used by all requests that reference this wallet.

With this `walletId` we can start polling with the status API until the wallet becomes ready. The polling will be executed every 3 seconds, then we change the object state when it becomes ready. Any wallet state change emits a 'state' event.

If this wallet was already started in the past, it will already be ready and the POST request will return the status 'READY'. Then we won't need the polling phase, the wallet state will automatically be changed to ready.

### Wallet Status

The `HathorWallet` object will have a `status()` method that returns if the wallet is ready to be used, i.e. if it was already fully loaded by the wallet-service. This method uses the `/wallet` GET API.

This method is used for polling the wallet status after starting it. After the status becomes ready, we emit an event of status change and the APIs can be used.

### Get balance

The `HathorWallet` object will have a `getBalance(options: { token?: string } = {})` method that returns the locked and available balance for each token. If token is `null` we return the balance for HTR. 

### Get addresses

The `HathorWallet` object will have a `getAllAddresses()` method that returns the addresses of the wallet, the index and number of transactions of each address. 

### Get history

The `HathorWallet` object will have a `getTxHistory(options: { token?: string } = {})` method that returns the addresses of the wallet, the index and number of transactions of each address. 

### Create a transaction

We have two methods to send a transaction, (i) `sendTransaction(address, value, options: { token: string | null, changeAddress: string | null } = { token: '00', changeAddress: null })` which sends a transaction to a single output, and (ii) `sendManyOutputsTransaction(outputs, options = { inputs: [], changeAddress: null })` which can have multiple outputs and select the inputs.

Both methods create and send the transaction in 4 steps:

1. Create a tx proposal: we send the inputs and outputs to the wallet service that locks the utxos in its db and returns an ID of the proposal and the path of each address being spent, so we can know which private key will be used to sign the inputs.
2. Complete tx: with each utxo address path we set each input data with the signature and public key, then we complete the tx with the timestamp and weight.
3. Mine tx: we send the transaction to the tx mining service and wait until it's mined to get the corresponding nonce and parents.
4. Update tx proposal: we send the updated information to the tx proposal, which creates the full tx, validates it and push to the full node.

### Token transactions

Create a token, mint, melt, delegate mint, delegate melt, destroy mint and destroy melt actions.

TODO the design for this implementation in wallet service is in final review and I will update this design here as soon as the implementation is released

### Real time update

https://github.com/HathorNetwork/hathor-wallet-service/issues/50

### Any storage refactor

With the new integration, most of the data saved on wallet lib storage won't be need anymore. We should have another design to study in deep if we can fully remove the storage or maybe have just some interfaces for the wallet to use it, while the lib have no data itself.

### Features that still need other APIs in the wallet service

- getCurrentAddress: https://github.com/HathorNetwork/hathor-wallet-service/issues/38
- getAddressIndex: https://github.com/HathorNetwork/hathor-wallet-service/issues/39
- isAddressMine: https://github.com/HathorNetwork/hathor-wallet-service/issues/57
- getTx: https://github.com/HathorNetwork/hathor-wallet-service/issues/40
- getAddressInfo: https://github.com/HathorNetwork/hathor-wallet-service/issues/42
- getUtxos: https://github.com/HathorNetwork/hathor-wallet-service/issues/41
- consolidateUtxos: depends on the one above.

## Implementation PR

https://github.com/HathorNetwork/hathor-wallet-lib/pull/184
I didn't create a PR for the headless changes because the wallet service currently does not support most of the headless features. However the branch `feat/wallet-service-lib` has the changes to test the integration with the methods above.

## Unresolved questions

1. Are we going to store the private keys of the wallets in the lib? I don't think we should do that in the lib. The wallet itself should take care of the private key encryption and storage. How do we sign the input if we don't store the private key? For now I am saving the seed.
2. Is it useful to have a method to return the balance of ALL tokens at once? I don't think so.

**Comment by andreabadesso** [comment]
In regards to the "unsolved questions":

> Are we going to store the private keys of the wallets in the lib? I don't think we should do that in the lib. The wallet itself should take care of the private key encryption and storage. How do we sign the input if we don't store the private key? For now, I am saving the seed.

I agree that the lib shouldn't worry about security and storage. The method to sign the input should be static and receive the input and the private key to be signed, returning the signed data

> Is it useful to have a method to return the balance of ALL tokens at once? I don't think so.

We currently don't have that API on the wallet-service, but I think it would be nice to have, maybe not for the wallets because in the current user interface we only show one token at a time, but for use cases that will consume the APIs through the wallet-lib this might be useful. Not sure if this should be developed without anyone asking for it tho

**Comment by pedroferreira1** [comment]
> I agree that the lib shouldn't worry about security and storage. I think that the method to sign the input should be static and receive the input and the private key to be signed, returning the signed data

Created an issue to debate this.

> We currently don't have that API on the wallet-service, but I think it would be nice to have, maybe not for the wallets because in the current user interface we only show one token at a time, but for use cases that will consume the APIs through the wallet-lib this might be useful. Not sure if this should be developed without anyone asking for it tho

Agreed. Will keep only filtered by token for now.

**Comment by pedroferreira1** [comment]
This design basically describes what was done in the PR #184 that was merged, then I will close it.
