### ISSUE TITLE
Handle block reward locks when choosing inputs of a tx and calculating balance

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-lib#35]
The wallet-lib will get the height of the network when calculating if an utxo can be spent (to check if the block reward is locked). Besides that, we will calculate the balance in real time considering the height of the network.

To do it we must update codes in 4 repositories: full node, wallet lib, wallet desktop and wallet mobile.

- **Full node:** we need to have an API where we could get the current height of the network. Besides that we need also to have the height sent in the metrics ws message.
  - **Issue:** https://github.com/HathorNetwork/hathor-core/issues/45
  - **MRs:**
    - **Get height from API:** https://gitlab.com/HathorNetwork/hathor-python/merge_requests/359
    - **Send height on ws:** https://gitlab.com/HathorNetwork/hathor-python/merge_requests/360

- **Wallet lib:** we need to update the method that check if an utxo can be spent to consider the height of the network getting the value from the API. We also need to consider the height when calculating the balance.
  - **Issue:** https://github.com/HathorNetwork/hathor-wallet-lib/issues/35
  - **PR:** https://github.com/HathorNetwork/hathor-wallet-lib/pull/40

- **Wallet desktop:** now methods to prepare data to be sent is async because of the API request to get network height, so we need to do this refactor. Besides that we need to get current height from API and save in redux to calculate balance in real time.
  - **PR:** Prepare send tokens data and calculate balance:
    - https://github.com/HathorNetwork/hathor-wallet/pull/65

- **Wallet mobile:** now methods to prepare data to be sent is async because of the API request to get network height, so we need to do this refactor. Besides that we need to get current height from API and save in redux to calculate balance in real time.
  - **PR:** Prepare send tokens data and calculate balance:
    - https://github.com/HathorNetwork/hathor-wallet-mobile/pull/39

**Comment by msbrogli** [comment]
All MRs and PRs were merged.
