### ISSUE TITLE
Refactor to make it easier to use the lib create a wallet

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet-lib#41]
Ideas:

- Create classes for each object type, so we would have a full description of their attributes and types.

**Comment by pedroferreira1** [comment]
@msbrogli 

@obiyankenobi had already created an issue to implement the lib refactor (https://github.com/HathorNetwork/hathor-wallet-lib/issues/30). I think we should keep only one, what do you think?

Maybe move this idea to that issue and keep the discussions there.

**Comment by obiyankenobi** [comment]
I agree, we should close this one and just use the other.

**Comment by obiyankenobi** [comment]
Duplicate #30
