### ISSUE TITLE
refactor: Migrate the HathorWallet facade from hathor-wallet-headless to hathor-wallet-lib

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet-lib#46]
PR lib: https://github.com/HathorNetwork/hathor-wallet-lib/pull/50
PR wallet headless: https://github.com/HathorNetwork/hathor-wallet-headless/pull/5

**Comment by pedroferreira1** [comment]
PR lib: https://github.com/HathorNetwork/hathor-wallet-lib/pull/50
PR wallet headless: https://github.com/HathorNetwork/hathor-wallet-headless/pull/5

**Comment by msbrogli** [comment]
@pedroferreira1 We should update the Twitter bot as well, right?

**Comment by pedroferreira1** [comment]
> @pedroferreira1 We should update the Twitter bot as well, right?

Yes, we should. I've create an issue on twitter bot repository and added to our backlog to do this later. (https://github.com/HathorNetwork/twitter-hathor-bot/issues/4)
