### ISSUE TITLE
[Design] System storage

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/hathor-wallet-lib#517]
# Summary

A storage for the wallet system that does not belong to any specific wallet instance.
This will help manage a wallet system but will not be required to run a wallet.

# Motivation

The main motivation is because of an impasse on the persistent storage design.
We require the system to check if we have any wallets available, and if so, which ones.
We could initialize the storage but for persistent storages, i.e. LevelDB,  this requires the change path xpubkey of the wallet, this was done so that we would not rely on an arbitrary name for the wallet storage directory which could be changed by the user and cause the wallet to not find its storage.

The impasse consists of requiring a started storage to get data from, but to start a storage we need data from inside the storage.
To solve this we will create a storage that is not bound to a specific wallet instance, this storage will be used to store system configurations, e.g. wheather the user approved to send error data to Hathor, or data to provide an easier wallet implementation, e.g. the list of wallets that are available to the user, etc.

# Guide-level explanation

We will create a storage interface that is not bound to a specific wallet instance.
This storage interface will be used to store system configurations, e.g. wheather the user approved to send error data to Hathor, or data to provide an easier wallet implementation, e.g. the list of wallets that are available to the user, etc.

```ts
interface ISavedWallet {
    name: string;
    pubkey: string;
    // Allow the possibility to start a wallet from a saved accessData
    // This should only be used if we use a persistent system storage but memory storage for wallets
    accessData?: IWalletAccessData;
}

interface ISystemStore {
    // Generic storage methods to store wallet specific data
    getItem(key: string): Promise<any | null>;
    setItem(key: string, value: string): Promise<void>;

    // Save a wallet to the list of available wallets
    saveWallet(wallet: ISavedWallet): Promise<void>;

    // Returns the list of wallets that are available to the user
    getSavedWallets(): Promise<ISavedWallet[]>;

    // Remove saved wallet from the list of available wallets
    deleteSavedWallet(name: string): Promise<void>;

    // Get a wallet storage by its name
    // This will help starting wallets from the list of available wallets
    startWalletStorage(name: string): Promise<IStorage | null>;

    // Manage initialized wallets, this should only be used in memory
    addInitializedWallet(walletId: string, wallet: HathorWallet): Promise<void>;
    getInitializedWallet(walletId: string): Promise<HathorWallet | null>;
    stopInitializedWallet(walletId: string): Promise<void>;
}
```

We will implement the memory and leveldb variants of the system storage (i.e. `MemorySystemStore`, `LevelDBSystemStore`), this is enough to cover the use cases we currently have but any wallet can implement its own system storage using the interface above.

# Reference-level explanation

## MemorySystemStore

The memory system store will hold:

- `Map<string, ISavedWallet>` of saved wallets by name.
- `Map<string, any>` of key-value pairs to be used with the generic item methods.
- `Map<string, HathorWallet>` of wallet instances by name.

This implementation is very straightforward since we only have to implement listing and saving wallets in this initial version.

## LevelDBSystemStore

The leveldb system store will divide the database in 2, each with their own prefix:

- `savedwallets:<name>` prefix will hold the list of wallets by name
- `generic:<key>` prefix will hold the generic key-value pairs

We will also have a `Map<string, HathorWallet>` of wallet instances by name, this is needed to manage the initialized wallets.
Since an initialized wallet cannot be persisted, we will only store the wallet instance in memory.

# Prior art

Some wallets already have implementations that serve as a system storage, for instance:

- Wallet mobile uses `AsyncStorage` as a persistent storage to hold which biometric options the device has and other configurations.
- Wallet headless has a `initializedWallets` map of wallet-ids to initialized wallet instances.
- Wallet desktop uses localStorage to hold the list of wallets that are available to the user.

# Rationale and alternatives

- We can let the wallet implement the system management themselves, but this will lead to duplicated code and will make it harder to implement new features if we have to implement them in all wallets.
- Community created wallets may have their own way to manage the "system" but this is not an issue since the system storage is optional and not required to run a wallet.

# Future possibilities

There are some features that are implemented in the wallets that could be moved to the system storage if we want them to be available to all wallets.

**Comment by msbrogli** [comment]
As discussed with @r4mmer, I feel that this storage should be designed and implemented by each app since it will store app data (not wallet data). The wallet id (also called `pubkey` in this design) is part of the app data.

We might also add a `list_wallets()` method to the wallet lib.

Last, we shouldn't have a copy of the access data in the app storage. The only thing the app needs to store is the wallet id. All other wallet data should be stored only in the wallet storage.

**Comment by tuliomir** [comment]
Considering that the implementation should be a responsibility for the app, would it be a good idea to create only the interfaces on the lib? Something similar to what is already done on `IStorage`:

https://github.com/HathorNetwork/hathor-wallet-lib/blob/796b8d17c3f323b86c752d867abb1ae9894b0a9b/src/types.ts#L333

I think there may be benefits in having a standardized suggested approach, especially when developing new features, even though the implementation may vary on each app.

Also, we already have a way to generate a `walletId` from an `xpub` on the Wallet Service facade of the lib: the [`getWalletIdFromXPub` method](https://github.com/HathorNetwork/hathor-wallet-lib/blob/112667304d313a58bc1d96837983c0679d6f8ada/src/wallet/wallet.ts#L280-L291)

**Comment by r4mmer** [comment]
This design has been discarded since we understand that wallet management should be the responsibility of the wallet implementation since it can use other formats and be more flexible to introduce features exclusive to the system.
