### ISSUE TITLE
[Design] Storage: Data migration between versions

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet-lib#65]
## Design

Storage's keys should follow these rules:

- All keys should be prefixed with the version of the storage, e.g., v1-, v2-, v3-, and so on.
- All versions must have at least one key in common: status.
- The statuses must be either `current`, `migrating`, or `cleaning`.

When a brand new wallet is run, the storage will be empty. So, it is easy to detect it.

Let's say a given Hathor Wallet is in storage version v7-, it should look for v7-status. If it is not found, it will search which previous version is available. So, it will look for v6-status, then v5-status, and so on. If none is found, it shows an error message to the user. If v4-status is found, then the wallet knows it must run v4_to_v5(), v5_to_v6(), and v6_to_v7(). All intermediary states will be properly cleaned up (v5 and v6), remaining only v4- and v7- in the storage. Finally, if the storages initiates correctly, it can cleanup v4- keys. Otherwise, it keeps it there so previous version still works.

During the migrations, `v5-`, `v6-` (before they are cleaned up), and `v7-` will have status `migrating`. After the migration is finished and the wallet initiates, v7 should become `current` and v4 should become `cleaning`.

Using this approach, we don't need to implement any backward migration between versions.

We still need a description of when the wallet is "correctly started". One simple definition is:

1. When it successfully loads the history of transactions, and
2. When it can access the xpriv (if the password/PIN is required, we should request it from the user).

### Migration from v0 to v1

Initially, we must implement a `v0_to_v1()` method that will migrate from keys with no prefix to keys with `v1-` prefix. We will need a special `v0_cleanup()` that must cleanup all old keys after the migration is successful.

## Initial description of this issue (to start the discussion)

`Storage` has a simple and straightforward interface that includes a `getItem` and `setItem`. I think we should create a key `_version` that will start as null (or undefined) and should be increased on every change we do in the storage.

The storage version may have a major and minor numbers. Major numbers should be increased when incompatible changes are applied, while minor numbers must be compatible. It is useful for identifying incompatibilities and showing the best error message for users.

The final design is impacted by the following discussion points:

1. After migrating to a newer version of Hathor Wallet, should previous versions also work? All of them or just the immediate previous one? For example, user has updated their wallet for v0.14.0. Should v0.13.0 work? What about v0.5.0?

**Comment by msbrogli** [comment]
I think it may be important to keep support for previous versions but not all of them. Running the immediate previous version may be enough.

**Comment by obiyankenobi** [comment]
We could have a chain of updates, so it would always work, regardless if you skip lots of updates.

So let's say we have versions 1, 2, 3, 4 (using this to make it easier). 4 is the latest version. On our update storage function:

```js
updateStorage() {
  if (version === 1) {
    // update 1 -> 2
    version = 2;
  }

  if (version === 2) {
    // update 2 -> 3
    version = 3
  }

  if (version === 3) {
    // update 3 -> 4
    version = 4
  }
}
```

Whenever we make a new storage version, we'd just add a new `if` in this function.

**Comment by jansegre** [comment]
I don't know if we can make data update operations atomically. If we can't we should consider an even safer mechanism, because if the wallet stops during an upgrade it can be left in an unrecoverable state, or at least a state that is very hard to implement a recovery from.

One way to do this safer is isolating the versioned storage, and implementing migrations to move between them. Isolating versioned storage could be made by adding a version prefix to the keys. And a migration could be stateful, and only remove the previous version storage after the migration is completed successfully. This way when the app is started the storage engine would check if the currently required storage is available and migrated, if not it would search for the last version and try to migrate to the latest one, migration by migration. If any of them fails, the user could be prompted to try again, reset the storage, be warned that there was a previous failed migration, or even suggested an app downgrade if possible.

**Comment by pedroferreira1** [comment]
> After migrating to a newer version of Hathor Wallet, should previous versions also work? All of them or just the immediate previous one? For example, user has updated their wallet for v0.14.0. Should v0.13.0 work? What about v0.5.0?

I think the automatic storage update should be from the last incompatible version, or we should implement a more robust mechanism of storage update, as @jansegre suggested.

In the other cases, we could use the mechanism we currently have, where we set the user to reset the wallet, in case it has a really old version.

**Comment by msbrogli** [comment]
@obiyankenobi I think the final design will be a mix of what you said and @jansegre said.

What about this storage model:

- All keys should be prefixed with the version of the storage, e.g., `v1-`, `v2-`, `v3-`, and so on.
- All versions must have at least one key in common: `status`.

So, let's say a given Hathor Wallet is in storage version `v7-`, it should look for `v7-status`. If it is not found, it will search which previous version is available. So, it will look for `v6-status`, then `v5-status`, and so on. If none is found, it shows an error message to the user. If `v4-status` is found, then the wallet knows it must run `v4_to_v5()`, `v5_to_v6()`, and `v6_to_v7()`. All intermediary states will be properly cleaned up (v5 and v6), remaining only `v4-` and `v7-` in the storage. Finally, if the storages initiates correctly, it can cleanup `v4-` keys. Otherwise, it keeps it there so previous version still works.

This way, we don't need to implement any backward migration between versions.

**Comment by obiyankenobi** [comment]
It looks good, just 2 things:

> If none is found, it shows an error message to the user.

This will happen on a new wallet (after installing the app) or after a user resets the wallet.

> Finally, if the storages initiates correctly

I'm not sure how easy it is to check this. How do we detect a storage was initiated correctly?

**Comment by msbrogli** [comment]
When a brand new wallet is run, the storage will be empty.

I think the available statuses should be `running`, `migrating`, and `waiting-to-be-cleaned`.

So, during the migrations, `v5-`, `v6-` (before they are cleaned up), and `v7-` will have status `migrating`. After the migration is finished and the wallet initiates, v7 should become `running` and v4 should become `waiting-to-be-cleaned`.

I agree that we need a better definition of "initiated correctly". I'd say if it loads the history and it passes a generic method `verify_wallet()`, it is good. The verify wallet should try to access the xpriv (if the password/PIN is required, we can either skip it or ask the user for it).

I know this criteria may fail, but I think it should be enough for now.

**Comment by pedroferreira1** [comment]
For me it's good, I still think this `verify_wallet` method should be discussed further but it's the only missing piece for me.

About @obiyankenobi comment here
> This will happen on a new wallet (after installing the app) or after a user resets the wallet.

We decide which keys we want to clean when resetting the wallet, so we could just leave this status key in the storage. And a brand new wallet I agree, we won't have anything but in the check we can just validate in which version the storage is, if there are no versions, we set the current wallet version on it.

For me it's good. And after we've done this change, we need to add to the QA the data migration test also.

**Comment by msbrogli** [comment]
@obiyankenobi @pedroferreira1 @jansegre Can you review it again, please? If you approve it, please leave a message.

**Comment by obiyankenobi** [comment]
Approved.

**Comment by jansegre** [comment]
The overalls look good to me. I'd maybe nitpick on the states and their names but I approve the strategy and mechanism.

**Comment by pedroferreira1** [comment]
Approved.

**Comment by msbrogli** [comment]
Following @jansegre's suggestion, I renamed the states to `current`, `migrating`, or `cleaning`.

**Comment by msbrogli** [comment]
I also added a description of the state machine.
