### ISSUE TITLE
Implement changes to the wallets to use the Transaction Mining API

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-lib#73]
Lib: https://github.com/HathorNetwork/hathor-wallet-lib/pull/74
Wallet desktop: https://github.com/HathorNetwork/hathor-wallet/pull/119
Wallet mobile: https://github.com/HathorNetwork/hathor-wallet-mobile/pull/61
Wallet headless: https://github.com/HathorNetwork/hathor-wallet-headless/pull/14
Full node: https://gitlab.com/HathorNetwork/hathor-python/-/merge_requests/404

**Comment by pedroferreira1** [comment]
@msbrogli @jansegre @obiyankenobi 

Following Yan's suggestion to improve the sending tx UI, I added the loading messages on the PIN modal, instead of closing the modal and showing them on the screen. In the end there will be a success message and the user will click a button to close the modal and go back to the list (nowadays it's weird sometimes because there is no success message and you just go back to the screen).

After this test, I do prefer everything on the modal, as on the second gif. What are your thoughts?

Everything is in a component, I just need to add it in all other screens.

**Comment by obiyankenobi** [comment]
Yeah, I think this way is much better, as it also prevents the user from leaving the screen in the middle of the process.

We should even prevent him from closing the modal in the process. Not sure if this is the behavior already.

The error message is also displayed in the modal?

**Comment by msbrogli** [comment]
Well done!

**Comment by jansegre** [comment]
It's looking good.

**Comment by msbrogli** [comment]
I just reviewed all PRs and they seem good to me.
